AWSTemplateFormatVersion: '2010-09-09'
# Version 5
# Fixes issue with Lambda function used to push stack to new account.   Originally used hardcoded stackset name
# StackSet name now defined as a parameter during creation
#

Description: Control Tower Lifecycle Events
Parameters:
  RoleCreationDelayTimer:
    Description: Delay timer wait for role creation before registering acct (Time in seconds)
    Type: Number
    MaxValue: 800
    Default: 60
  FalconClientId:
    Description: Your Falcon OAuth2 API Key.
    NoEcho: 'true'
    Type: String

  FalconSecret:
    Description: Your Falcon OAuth2 API Secret.
    NoEcho: 'true'
    Type: String

  CrowdStrikeCloud:
    Default: us1
    Description:  The CrowdStrike Cloud your CID is hosted in us1, us2 or eu
    Type: String
    AllowedValues:
      - us1
      - us2
      - eu
  RoleName:
    Description: IAM Role Name (May be modified)
    Type: String
    Default: CrowdStrikeFalcon

  ExternalID:
    Description: External ID associated with the role assumed by CrowdStrike
    Type: String

  StackSetName:
    Description: The name of the CrowdStrike Discover StackSet
    Type: String
    Default: CrowdStrike-Discover-Stackset

  LogArchiveAccount:
    Type: String
    Description: AccountId of Log Archive Bucket

  LogArchiveBucketRegion:
    Type: String
    Description: Log Archive Bucket Region

Mappings:
  S3perRegion:
    us-east-1:
      NAME: crowdstrike-sa-resources-ct-us-east-1
    us-east-2:
      NAME: crowdstrike-sa-resources-ct-us-east-2
    us-west-2:
      NAME: crowdstrike-sa-resources-ct-us-west-2
    eu-west-1:
      NAME: crowdstrike-sa-resources-ct-eu-west-1
    ap-southeast-2:
      NAME: crowdstrike-sa-resources-ct-ap-southeast-2
  CSCloud:
    us1:
      CSAssumingRoleName: CS-Prod-HG-CsCloudconnectaws
      CSAccount: 292230061137
    us2:
      CSAssumingRoleName: mav-gyr-main-s001-cs-cloudconnectaws
      CSAccount: 292230061137
    eu:
      CSAssumingRoleName: lion-lanner-main-s001-cs-cloudconnectaws
      CSAccount: 292230061137



Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: CrowdStrike Role Parameters.
        Parameters:
          - RoleName
      - Label:
          default: CrowdStrike Falcon API keys.
        Parameters:
          - FalconClientId
          - FalconSecret
      - Label:
          default: Log Archive Account Details
        Parameters:
          - LogArchiveAccount
          - LogArchiveBucketRegion
Resources:
  CrowdStrikeCredentials:
    Type: AWS::SecretsManager::Secret
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W77
            reason: "Not required to be shared across accounts."
    Properties:
      Description: CrowdStrike Credentials
      Name: !Join
        - '-'
        - - !Ref 'AWS::StackName'
          - CrowdStrikeAPISecret
      SecretString:
        Fn::Join:
          - ''
          - - '{"FalconClientId":"'
            - Ref: FalconClientId
            - '","FalconSecret": "'
            - Ref: FalconSecret
            - '"}'

  launchLambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Wildcard required to list secrets"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            Condition: { }
      Path: /
      Policies:
        - PolicyName: Get_Values
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Sid: VisualEditor1
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref CrowdStrikeCredentials
        - PolicyName: List_secrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Sid: VisualEditor2
              Effect: Allow
              Action:
                - secretsmanager:ListSecrets
              Resource: '*'
        - PolicyName: CloudFormation_ops
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Sid: VisualEditor2
              Effect: Allow
              Action:
                - cloudformation:CreateStackSet
                - cloudformation:CreateStackInstances
                - cloudformation:DescribeStackSet
                - cloudformation:ListStackInstances
                - cloudformation:DeleteStackInstances
                - cloudformation:DeleteStackSet
              Resource: !Join [ ':', [ 'arn:aws:cloudformation', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'stackset/*:*' ] ]
        - PolicyName: Pass_Role
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Sid: VisualEditor3
              Effect: Allow
              Action:
                - iam:PassRole
              Resource: !Join [ ':', [ 'arn:aws:iam:', !Ref "AWS::AccountId", 'role/service-role/AWSControlTowerStackSetRole' ] ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  permissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt "LambdaToLaunchStackSet.Arn"
      Principal: cloudformation.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"

  LambdaToLaunchStackSet:
    Type: 'AWS::Lambda::Function'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "Should not run inside a VPC as this is a custom resource"
          - id: W92
            reason: "Lambda will only run once in stackset lifecycle as it is a custom resource"
    DeletionPolicy: Delete
    Properties:
      Code:
        S3Bucket: !FindInMap [ S3perRegion, !Ref "AWS::Region", NAME ]
        S3Key: create_stackset_lambdav4.zip
      Layers:
        - !Ref lambdaLayer
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          StackSetName: !Ref StackSetName
          CrowdStrikeCloud: !Ref CrowdStrikeCloud
          RoleCreationDelayTimer: !Ref RoleCreationDelayTimer
          AwsRegion: !Ref AWS::Region
          LogArchiveAccount: !Ref LogArchiveAccount
          LogArchiveBucketRegion: !Ref LogArchiveBucketRegion
          RoleName: !Ref RoleName
          CSAccountNumber: !FindInMap [ CSCloud, !Ref CrowdStrikeCloud, CSAccount ]
          CSAssumingRoleName: !FindInMap [ CSCloud, !Ref CrowdStrikeCloud, CSAssumingRoleName ]
          CrowdstrikeCredentialsSecret: !Ref CrowdStrikeCredentials
      Handler: create_stackset_lambdav4.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Role: !GetAtt "launchLambdaRole.Arn"
      Timeout: 180
  TriggerLambda1:
    Type: 'Custom::TriggerLambda'
    Properties:
      FalconSecret: !Ref FalconSecret
      FalconClientId: !Ref FalconClientId
      ExternalID: !Ref ExternalID
      ServiceToken: !GetAtt
        - LambdaToLaunchStackSet
        - Arn
  lambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: !FindInMap [ S3perRegion, !Ref "AWS::Region", NAME ]
        S3Key: layer.zip
      Description: Layer for requests package
      LayerName: requests-package

  CrowdStrikeCaptureControlTowerLifeCycleEvents:
    Type: AWS::Events::Rule
    Properties:
      Description: Capture Control Tower LifeCycle Events and Trigger an Action
      EventPattern:
        detail:
          eventName:
            - CreateManagedAccount
            - UpdateManagedAccount
          eventSource:
            - controltower.amazonaws.com
        detail-type:
          - AWS Service Event via CloudTrail
        source:
          - aws.controltower
      Name: CrowdStrikeCaptureControlTowerLifeCycleEvents
      State: ENABLED
      Targets:
        - Arn: !GetAtt "TriggerCustomizationsOnLifeCycleEvent.Arn"
          Id: IDCrowdStrikeCaptureControlTowerLifeCycleEvents

  LambdaRoleToCaptureEvents:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            Condition: { }
      Path: /
      Policies:
        - PolicyName: inline-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStackInstances'
                Resource: !Join [ ':',[ 'arn:aws:cloudformation', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'stackset/*:*' ] ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  TriggerCustomizationsOnLifeCycleEvent:
    Type: AWS::Lambda::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "Should not run inside a VPC as this is a custom resource"
          - id: W92
            reason: "Lambda will only run once in stackset lifecycle as it is a custom resource"
    Properties:
      Code:
        S3Bucket: !FindInMap [ S3perRegion, !Ref "AWS::Region", NAME ]
        S3Key: crowdstrikeAccts_lambdav4.zip
      Layers:
        - !Ref lambdaLayer
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          StackSetName: !Ref StackSetName

      Handler: crowdstrikeAccts_lambdav4.lambda_handler
      MemorySize: 128
      Role: !GetAtt "LambdaRoleToCaptureEvents.Arn"
      Runtime: python3.7
      Timeout: 60

  PermissionForEventsToInvokeLambdachk:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt "TriggerCustomizationsOnLifeCycleEvent.Arn"
      Principal: events.amazonaws.com
      SourceArn: !GetAtt "CrowdStrikeCaptureControlTowerLifeCycleEvents.Arn"
