AWSTemplateFormatVersion: '2010-09-09'
Description: Control Tower Lifecycle Events
Parameters:
  FalconClientId:
    Description: Your Falcon OAuth2 API Key.
    NoEcho: 'true'
    Type: String

  FalconSecret:
    Description: Your Falcon OAuth2 API Secret.
    NoEcho: 'true'
    Type: String

  ExternalId:
    Description: ExternalID Used for authenticating assume role requests.
    NoEcho: 'true'
    Type: String

  CSAccountNumber:
    Default: '292230061137'
    Description: CrowdStrike Account ID.
    Type: String


  RoleName:
    Description: IAM Role Name (May be modified)
    Type: String
    Default: CrowdStrikeFalcon
  CSAssumingRoleName:
    Type: String
    Description: Assuming IAM Role Name
    Default: CS-Prod-HG-CsCloudconnectaws
  LogArchiveAccount:
    Type: String
    Description: AccountId of Log Archive Bucket

  LogArchiveBucketRegion:
    Type: String
    Description: Log Archive Bucket Region

Mappings:
  S3perRegion:
    us-east-1:
      NAME: crowdstrike-sa-resources-ct-us-east-1
    us-east-2:
      NAME: crowdstrike-sa-resources-ct-us-east-2
    us-west-2:
      NAME: crowdstrike-sa-resources-ct-us-west-2
    eu-west-1:
      NAME: crowdstrike-sa-resources-ct-eu-west-1
    ap-southeast-2:
      NAME: crowdstrike-sa-resources-ct-ap-southeast-2

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: CrowdStrike Account Parameters. (Do Not Modify)
        Parameters:
          - CSAccountNumber
          - CSAssumingRoleName
      - Label:
          default: CrowdStrike Role Parameters.
        Parameters:
          - RoleName
          - ExternalId
      - Label:
          default: CrowdStrike Falcom API keys.
        Parameters:
           - FalconClientId
           - FalconSecret
      - Label:
          default: Log Archive Account Details
        Parameters:
          - LogArchiveAccount
          - LogArchiveBucketRegion
Resources:
  CrowdStrikeCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: CrowdStrike Credentials
      Name: CrowdStrikeAPISecret
      SecretString:
        Fn::Join:
        - ''
        - - '{"FalconClientId":"'
          - Ref: FalconClientId
          - '","FalconSecret": "'
          - Ref: FalconSecret
          - '"}'

  launchLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: launchLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            Condition: {}
      Path: /
      Policies:
        - PolicyName: Get_Values
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Sid: VisualEditor1
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref CrowdStrikeCredentials
        - PolicyName: List_secrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Sid: VisualEditor2
              Effect: Allow
              Action:
                - secretsmanager:ListSecrets
              Resource: '*'
        - PolicyName: CloudFormation_ops
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Sid: VisualEditor2
              Effect: Allow
              Action:
                - cloudformation:CreateStackSet
                - cloudformation:CreateStackInstances
                - cloudformation:DescribeStackSet
                - cloudformation:ListStackInstances
                - cloudformation:DeleteStackInstances
                - cloudformation:DeleteStackSet
              Resource: !Join [':', ['arn:aws:cloudformation', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'stackset/*:*']]
        - PolicyName: Pass_Role
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Sid: VisualEditor3
              Effect: Allow
              Action:
                - iam:PassRole
              Resource: !Join [':', ['arn:aws:iam:', !Ref "AWS::AccountId", 'role/service-role/AWSControlTowerStackSetRole']]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  permissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt "LambdaToLaunchStackSet.Arn"
      Principal: cloudformation.amazonaws.com
      SourceAccount: !Ref "AWS::AccountId"

  LambdaToLaunchStackSet:
    DependsOn:
      - "launchLambdaRole"
      - CrowdStrikeCredentials
    Type: 'AWS::Lambda::Function'
    DeletionPolicy: Delete
    Properties:
      Code:
        S3Bucket: !FindInMap [ S3perRegion, !Ref "AWS::Region", NAME ]
        S3Key: create_stackset_lambda.zip
      Layers:
        - !Ref lambdaLayer
      Environment:
        Variables:
          AwsRegion: !Ref AWS::Region
          LogArchiveAccount: !Ref LogArchiveAccount
          LogArchiveBucketRegion: !Ref LogArchiveBucketRegion
          RoleName : !Ref RoleName
          CSAccountNumber: !Ref CSAccountNumber
          CSAssumingRoleName: !Ref CSAssumingRoleName
          CrowdstrikeCredentialsSecret: !Ref CrowdStrikeCredentials
      Handler: create_stackset_lambda.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Role: !GetAtt "launchLambdaRole.Arn"
      Timeout: 180
  TriggerLambda1:
    Type: 'Custom::TriggerLambda'
    DependsOn:
      - LambdaToLaunchStackSet
      - "launchLambdaRole"
      - permissionForEventsToInvokeLambda
    Properties:
      FalconSecret: !Ref FalconSecret
      FalconClientId: !Ref FalconClientId
      ServiceToken: !GetAtt
        - LambdaToLaunchStackSet
        - Arn
  lambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: !FindInMap [ S3perRegion, !Ref "AWS::Region", NAME ]
        S3Key: layer.zip
      Description: Layer for requests package
      LayerName: requests-package

  CrowdStrikeCaptureControlTowerLifeCycleEvents:
    DependsOn:
    - TriggerCustomizationsOnLifeCycleEvent
    Type: AWS::Events::Rule
    Properties:
      Description: Capture Control Tower LifeCycle Events and Trigger an Action
      EventPattern:
        detail:
          eventName:
          - CreateManagedAccount
          - UpdateManagedAccount
          eventSource:
          - controltower.amazonaws.com
        detail-type:
        - AWS Service Event via CloudTrail
        source:
        - aws.controltower
      Name: CrowdStrikeCaptureControlTowerLifeCycleEvents
      State: ENABLED
      Targets:
      - Arn: !GetAtt "TriggerCustomizationsOnLifeCycleEvent.Arn"
        Id: IDCrowdStrikeCaptureControlTowerLifeCycleEvents

  LambdaRoleToCaptureEvents:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaRoleToCaptureEvents
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            Condition: {}
      Path: /
      Policies:
        - PolicyName: inline-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStackInstances'
                Resource: !Join [':',['arn:aws:cloudformation', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'stackset/*:*']]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  TriggerCustomizationsOnLifeCycleEvent:
    DependsOn:
    - LambdaRoleToCaptureEvents
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !FindInMap [ S3perRegion, !Ref "AWS::Region", NAME ]
        S3Key: crowdstrikeAccts_lambda.zip
      Layers:
        - !Ref lambdaLayer
      Environment:
        Variables:
          RoleName: !Ref RoleName
          CSAccountNumber: !Ref CSAccountNumber
          CSAssumingRoleName: !Ref CSAssumingRoleName
      Handler: crowdstrikeAccts_lambda.lambda_handler
      MemorySize: 128
      Role: !GetAtt "LambdaRoleToCaptureEvents.Arn"
      Runtime: python3.7
      Timeout: 60

  PermissionForEventsToInvokeLambdachk:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt "TriggerCustomizationsOnLifeCycleEvent.Arn"
      Principal: events.amazonaws.com
      SourceArn: !GetAtt "CrowdStrikeCaptureControlTowerLifeCycleEvents.Arn"
