AWSTemplateFormatVersion: '2010-09-09'
Description: This template sets up a cross account IAM role in order to enable CrowdStrike Falcon Discover and registers the Account within the Falcon platform.

Outputs:
  RoleARN:
    Description: The ARN of the role that can be assumed by the other account.
    Value: !GetAtt 'iamRole.Arn'



Parameters:
  CrowdStrikeCloud:
    Default: usgov1
    Description: The CrowdStrike Cloud usgov1
    Type: String
    AllowedValues:
      - usgov1

  RoleCreationDelayTimer:
    Description: Delay timer wait for role creation before registering acct (Time in seconds)
    Type: Number
    MaxValue: 800
    Default: 60

  FalconClientId:
    Description: Falcon OAuth2 Client ID.
    Type: String
    NoEcho: true

  FalconSecret:
    Description: Falcon Oath2 API secret.
    Type: String
    NoEcho: true

  ExternalID:
    Description: The External ID that will be required to assume the role.
    MinLength: '1'
    Type: String

  RoleName:
    Description: The name of the cross account IAM role to be created.
    MinLength: '1'
    Type: String

  CSAccountNumber:
    AllowedPattern: '[0-9]+'
    Description: The 12 digit AWS account number to grant access to.
    MaxLength: '12'
    MinLength: '12'
    Type: String

  CSAssumingRoleName:
    Description: Name of the IAM role used within CrowdStrike to assume access to your account.
    Type: String

  LogArchiveAccount:
    Type: String
    Description: AccountId of Log Archive Bucket

  LogArchiveBucketRegion:
    Type: String
    Description: Log archive bucket region

  LogArchiveBucketName:
    Type: String
    Description: Name of bucket containing CloudTrail Logs

  S3Bucket:
    Type: String
    Description: The S3 bucket that contains the lambda zip files

Conditions:
  IsLogArchiveAccount: !Equals
    - !Ref LogArchiveAccount
    - !Ref AWS::AccountId

Resources:
  iamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref 'RoleName'
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalID: !Ref 'ExternalID'
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':iam::'
                  - !Ref 'CSAccountNumber'
                  - :role/
                  - !Ref 'CSAssumingRoleName'
            Sid: ''
        Version: '2012-10-17'
      Path: /
  iamPolicyDescribeAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: FalconDiscoverAccess
      PolicyDocument:
        Statement:
          - Action:
              - ec2:DescribeInstances
              - ec2:DescribeImages
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribeVolumes
              - ec2:DescribeVpcs
              - ec2:DescribeRegions
              - ec2:DescribeSubnets
              - ec2:DescribeNetworkAcls
              - ec2:DescribeSecurityGroups
              - iam:ListAccountAliases
            Effect: Allow
            Resource: '*'
            Sid: ''
        Version: '2012-10-17'
      Roles:
        - !Ref 'iamRole'

  iamPolicyS3CTAccess:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsLogArchiveAccount
    Properties:
      ManagedPolicyName: FalconCloudTrailAccess
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join [ '', [ 'arn:', !Ref 'AWS::Partition', ':s3:::', !Ref 'LogArchiveBucketName', '/*'] ]
            Sid: ''
        Version: '2012-10-17'
      Roles:
        - !Ref 'iamRole'

  lambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: !Ref S3Bucket
        S3Key: falconpy-layer.zip
      Description: Layer for falconpy package
      LayerName: falconpy-package

  manageInstanceFalconAPI:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          CrowdStrikeCloud: !Ref CrowdStrikeCloud
          LogArchiveAccount: !Ref LogArchiveAccount
          cloudtrail_bucket_region: !Ref LogArchiveBucketRegion
          iam_role_arn: !GetAtt 'iamRole.Arn'
          CSAccountNumber: !Ref CSAccountNumber
          CSAssumingRoleName: !Ref CSAssumingRoleName
          LocalAccount: !Ref AWS::AccountId
          aws_region: !Ref AWS::Region
          delay_timer: !Ref RoleCreationDelayTimer
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: register_org_account.zip
      Layers:
        - !Ref lambdaLayer
      Handler: register_org_account.lambda_handler
      MemorySize: 128
      Role: !GetAtt "CrowdStrikeRegisterAcctLambdaRole.Arn"
      Runtime: python3.9
      Timeout: 900

  TriggerLambda:
    Type: 'Custom::TriggerLambda'
    DependsOn:
      - CrowdStrikeRegisterAcctLambdaRole
    Properties:
      FalconSecret: !Ref FalconSecret
      FalconClientId: !Ref FalconClientId
      ExternalID: !Ref ExternalID
      ServiceToken: !GetAtt
        - manageInstanceFalconAPI
        - Arn
        
  CrowdStrikeRegisterAcctLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaExecutionRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - '*'



